language: node_js
node_js:
  - lts/*
cache: npm
script:
  - npm run deploy
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: "56884598a2014faf71ac4c8ce00e2f75bcc0bbc8"
