language: node_js
node_js:
  - lts/*
cache: npm
script:
  - npm run deploy
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $access_token # Set in the settings page of your repository, as a secure variable
